# Kubernetes Deployment + Kubernetes Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-webapp
  labels:
    app: app-webapp
spec:
  #
  #
  #
  replicas: 1
  # This helps Kubernetes know
  # which Pod( replica)s belong to the currently-being-configured Deployment.
  selector:
    matchLabels:
      app: app-webapp
  # The following defines a blueprint for Kubernetes Pods.
  # (
  # In other words (and for the sake of emphasizing the point):
  # Everything within the next stanza/section constitutes
  # a configuration of a Kubernetes Pod,
  # with that configuration/stanza/section residing
  # within the configuration of the (currently-being-configured) Kubernetes Deployment.
  # )
  template:
    metadata:
      # The following is required for Pods.
      # (
      # When there are multiple replicas of the same Pod,
      # each Pod will be assigned a unique name (by Kubernetes).
      # (Utilizing) A `labels:` stanza makes it possible to
      # identify all Pod replicas of the same (software) application.
      # Labels do not guarantee uniqueness
      # but establish an association between a Deployment and to all its Pod replicas.
      # )
      #
      # (
      # For other components (like Deployment(?), ConfigMap, etc.),
      # the `labels:` stanza is optional,
      # but it is good practice to utilize it.
      # )
      labels:
        app: app-webapp
    spec:
      # There can be multiple containers in a pod
      # but, mostly, one main application per pod.
      containers:
      - name: container-mini-jira-2-webapp
        image: image-mini-jira-2:2024-01-01-10-35 
        ports:
        - containerPort: 5000
        env:
        # The first element in the following list is added
        # on the advice in https://stackoverflow.com/a/62224706 .
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-webapp
              key: django-secret-key
        - name: DB_ENGINE_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap-database
              key: db-engine-host
        - name: DB_ENGINE_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-database
              key: db-engine-port
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: secret-database
              key: secret-database-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secret-database
              key: secret-database-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-database
              key: secret-database-password
---
apiVersion: v1
kind: Service
metadata:
  name: service-webapp
spec:
  type: NodePort
  # This helps Kubernetes know
  # which Pods belong to this Service;
  # more specifically, this helps Kubernetes know
  # which (endpoint) Pods this Service should forward incoming requests to.
  selector:
    app: app-webapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      # The following must be between 30000 and 32767.
      nodePort: 30100
